import fs from 'node:fs';
import path from 'node:path';
import { MCP_HOSTS } from '../bootstrap/mcp_hosts.js';
import { REPO_CLASSES } from '../doctor/hygiene.js';
import { CLI_BIN } from './name.js';
import {
  KIT_COMMAND_TREE,
  KIT_TOP_LEVEL_COMMANDS,
  type CompletionValueKind,
  type KitCommandNode,
  type KitFlagSpec
} from './spec.js';

export { KIT_NESTED_COMMANDS, KIT_TOP_LEVEL_COMMANDS } from './spec.js';

export const KIT_COMPLETION_SHELLS = ['zsh', 'bash'] as const;
export type KitCompletionShell = (typeof KIT_COMPLETION_SHELLS)[number];

export function isCompletionShell(value: string | undefined): value is KitCompletionShell {
  return value !== undefined && (KIT_COMPLETION_SHELLS as readonly string[]).includes(value);
}

export function listMcpProfileNames(repoDir: string): string[] {
  const dir = path.join(repoDir, 'mcps', 'profiles');
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((name) => name.endsWith('.json'))
    .map((name) => name.replace(/\.json$/, ''))
    .sort();
}

export interface CompleteContext {
  mcpProfiles: readonly string[];
}

function dropBin(words: readonly string[]): string[] {
  if (words.length === 0) return [];
  const base = path.basename(words[0] ?? '');
  const bins: readonly string[] = [CLI_BIN, 'kit', 'kit.ts'];
  if (bins.includes(base)) return words.slice(1);
  return [...words];
}

function filterPrefix(candidates: readonly string[], prefix: string): string[] {
  if (!prefix) return [...candidates];
  return candidates.filter((value) => value.startsWith(prefix));
}

function resolveValues(kind: CompletionValueKind, ctx: CompleteContext): string[] {
  switch (kind) {
    case 'mcp-profiles':
      return [...ctx.mcpProfiles];
    case 'mcp-hosts':
      return [...MCP_HOSTS, 'all'];
    case 'repo-classes':
      return [...REPO_CLASSES];
  }
}

function flagNamed(node: KitCommandNode, token: string): KitFlagSpec | undefined {
  return node.flags?.find((flag) => flag.name === token);
}

export function completeKitLine(rawWords: readonly string[], ctx: CompleteContext): string[] {
  const words = dropBin(rawWords);
  const prefix = words.at(-1) ?? '';
  const prior = words.slice(0, -1);

  if (prior.length === 0) {
    return filterPrefix(KIT_TOP_LEVEL_COMMANDS, prefix);
  }

  const rootName = prior[0] ?? '';
  const root = KIT_COMMAND_TREE[rootName];
  if (!root) return [];

  let node: KitCommandNode = root;
  let i = 1;
  while (i < prior.length) {
    const tok = prior[i] ?? '';
    const flag = flagNamed(node, tok);
    if (flag) {
      i += flag.value ? 2 : 1;
      continue;
    }
    const sub = node.subs?.[tok];
    if (sub) {
      node = sub;
      i += 1;
      continue;
    }
    i += 1;
  }

  const lastPrior = prior.at(-1) ?? '';
  const valueFlag = flagNamed(node, lastPrior);
  if (valueFlag?.value) {
    return filterPrefix(resolveValues(valueFlag.value, ctx), prefix);
  }

  const out: string[] = [];
  if (node.subs && !prefix.startsWith('-')) {
    out.push(...Object.keys(node.subs));
  }
  if (node.positional && !prefix.startsWith('-')) {
    out.push(...resolveValues(node.positional, ctx));
  }
  if (node.flags && (prefix.startsWith('-') || prefix === '' || !node.subs)) {
    out.push(...node.flags.map((flag) => flag.name));
  }
  return filterPrefix([...new Set(out)], prefix);
}

export function renderZshCompletion(): string {
  return `#compdef ${CLI_BIN}
# Generated by ${CLI_BIN} completion zsh
# Thin stub: verbs and flags come from the live ${CLI_BIN} binary.

_wk() {
  local -a replies
  local bin="\${words[1]}"
  replies=(\${(f)"$("\$bin" __complete -- "\${words[@]}")"})
  if (( \${#replies} )); then
    compadd -- "\${replies[@]}"
    return
  fi
  _files
}

compdef _wk ${CLI_BIN}
`;
}

export function renderBashCompletion(): string {
  return `# Generated by ${CLI_BIN} completion bash
# Thin stub: verbs and flags come from the live ${CLI_BIN} binary.
_wk() {
  local bin="\${COMP_WORDS[0]}"
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  local -a replies
  while IFS= read -r line; do
    replies+=("\$line")
  done < <("\$bin" __complete -- "\${COMP_WORDS[@]}")
  if [[ \${#replies[@]} -gt 0 ]]; then
    COMPREPLY=( $(compgen -W "\${replies[*]}" -- "\$cur") )
    return
  fi
  COMPREPLY=( $(compgen -f -- "\$cur") )
}
complete -F _wk ${CLI_BIN}
`;
}

export function renderCompletion(shell: KitCompletionShell): string {
  return shell === 'zsh' ? renderZshCompletion() : renderBashCompletion();
}

export interface InstallCompletionsOptions {
  homedir: string;
  shells?: readonly KitCompletionShell[];
}

export interface InstallCompletionsResult {
  files: string[];
  snippet: string;
}

export function completionInstallPaths(homedir: string): Record<KitCompletionShell, string> {
  return {
    zsh: path.join(homedir, '.zfunc', '_wk'),
    bash: path.join(homedir, '.local', 'share', 'bash-completion', 'completions', 'wk')
  };
}

export function installCompletions(opts: InstallCompletionsOptions): InstallCompletionsResult {
  const shells = opts.shells ?? KIT_COMPLETION_SHELLS;
  const paths = completionInstallPaths(opts.homedir);
  const files: string[] = [];
  for (const shell of shells) {
    const dest = paths[shell];
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, renderCompletion(shell), 'utf8');
    files.push(dest);
  }
  const lines = ['Add this once, then open a new shell:'];
  if (shells.includes('zsh')) {
    lines.push(`  fpath=(${path.join(opts.homedir, '.zfunc')} $fpath)`);
    lines.push('  autoload -Uz compinit && compinit');
  }
  if (shells.includes('bash')) {
    lines.push(`  source ${paths.bash}`);
  }
  return { files, snippet: lines.join('\n') };
}
